apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u4ykxumaf-go 
  janus-idp.io/tekton: u4ykxumaf-go
  backstage.io/kubernetes-id: u4ykxumaf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u4ykxumaf-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  