apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u4ykxumaf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u4ykxumaf-go 
  name: u4ykxumaf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u4ykxumaf-go 
