apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u4ykxumaf-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:3a034d3e1149dcf8ddac7af893b05a88a505cf66@sha256:9adf8ed809bb18a618fa25c67a807d372db9de4d1aeb15bf109b553ce02086a4
          name: container-image
